name: dacn
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  shared_preferences: ^0.5.3+4
  flutter:
    sdk: flutter

  rxdart:
  flutter_circular_chart: ^0.1.0
  firebase_auth:
  firebase_database:
  google_sign_in:
  bloc:
  flutter_bloc: ^0.20.0
  equatable: ^0.2.3
  http: ^0.12.0+2
  sqflite: any
  path_provider: ^0.5.0+1
  font_awesome_flutter: ^8.4.0
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2
  tflite: ^1.0.4
  image: ^2.1.4


  flutter_svg: ^0.17.3+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jisho.db
    - assets/kanji_strokes/
    - assets/database.db
    - assets/etlcb_9b_model.tflite
    - assets/etlcb_9b_labels.txt
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
    - family: OtsutomeFont
      fonts:
        - asset: assets/fonts/otsutome_font.ttf
    - family: DroidJP
      fonts:
        - asset: assets/fonts/droid_sans_japanese.ttf

